#!/usr/bin/env python3
"""Bundles the browser editor (src/web/editor.html -> editor.js + the CRDT
compiled to JS) into build/web/editor.bundle.js, served at
/s/editor.js. The bundle is embedded into the server binary by C (#embed in
src/effects/db.c), so it never becomes a Bend String. Run by build.sh.""" 
import glob, os, subprocess, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = os.path.join(root, "build", "web")
subprocess.run(["rm", "-rf", out], check=True)
subprocess.run(["bend", os.path.join(root, "src/web/editor.html"), "-o", out], check=True, stdout=subprocess.DEVNULL)
chunks = glob.glob(os.path.join(out, "*.js"))
if len(chunks) != 1:
    sys.exit(f"expected one bundle chunk, got {chunks}")
js = open(chunks[0], encoding="utf-8").read()


dest = os.path.join(out, "editor.bundle.js")
os.replace(chunks[0], dest)
print(f"bundled editor: {len(js)} bytes -> {dest}")

# Vendored Datastar must be exactly the pinned release (vendor/datastar/README.md).
DATASTAR_SHA256 = "727844adfc825ee651fb93c544a2a739986f9a21820a94524b35f0cac470cf91"
import hashlib
got = hashlib.sha256(open(os.path.join(root, "vendor/datastar/datastar.js"), "rb").read()).hexdigest()
if got != DATASTAR_SHA256:
    sys.exit(f"vendor/datastar/datastar.js is not the pinned Datastar 1.0.4 (sha256 {got})")

# One version for all assets: pages link /s/<name>?v=<version>, and assets
# are cached forever, so any change to any asset changes every URL.
import hashlib
h = hashlib.sha256()
for p in [dest, os.path.join(root, "src/web/app.css"), os.path.join(root, "src/web/passkey.js"), os.path.join(root, "vendor/datastar/datastar.js")]:
    h.update(open(p, "rb").read())
ver = h.hexdigest()[:12]
os.makedirs(os.path.join(root, "src", "gen"), exist_ok=True)
gen = os.path.join(root, "src", "gen", "version.bend")
text = "# GENERATED by tools/bundle.py: a hash of the static assets. Do not edit.\nimport Base\n\ndef asset_version() -> String:\n  \"" + ver + "\"\n"
if not os.path.exists(gen) or open(gen).read() != text:
    open(gen, "w").write(text)
print(f"asset version {ver}")
